# Generated by Django 6.0.1 on 2026-03-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('autore', models.CharField(max_length=255)),
                ('anno_pubblicazione', models.IntegerField()),
                ('genere', models.CharField(max_length=100)),
                ('formato', models.CharField(max_length=50)),
                ('velocita', models.CharField(max_length=20)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('disponibile', models.BooleanField(default=True)),
                ('condizione', models.CharField(max_length=50)),
                ('discogs_id', models.IntegerField(blank=True, null=True)),
                ('copertina_url', models.URLField()),
            ],
        ),
    ]
