# Generated by Django 6.0.1 on 2026-03-31 11:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinili', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinile',
            options={'verbose_name_plural': 'Vinili'},
        ),
        migrations.CreateModel(
            name='Carrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='La quantità deve essere maggiore di 0')], verbose_name='Quantità')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vinile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinili.vinile')),
            ],
            options={
                'verbose_name_plural': 'Carrelli',
            },
        ),
        migrations.CreateModel(
            name='Possiede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acquisto', models.DateField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vinile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinili.vinile')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_wishlist', models.CharField(max_length=100)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DesideratoIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinili.vinile')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinili.wishlist')),
            ],
        ),
    ]
