# Generated by Django 6.0.1 on 2026-03-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinili', '0002_alter_vinile_options_carrello_possiede_wishlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possiede',
            name='data_acquisto',
        ),
    ]
