# Generated by Django 6.0.1 on 2026-04-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinili', '0003_remove_possiede_data_acquisto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Generi',
            },
        ),
        migrations.RemoveField(
            model_name='vinile',
            name='copertina_url',
        ),
        migrations.RemoveField(
            model_name='vinile',
            name='genere',
        ),
        migrations.AddField(
            model_name='vinile',
            name='copertina',
            field=models.ImageField(blank=True, null=True, upload_to='copertine_vinili/'),
        ),
        migrations.AlterField(
            model_name='vinile',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vinile',
            name='generi',
            field=models.ManyToManyField(to='vinili.genere'),
        ),
    ]
