# Generated by Django 6.0.1 on 2026-04-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinili', '0004_genere_remove_vinile_copertina_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Formati',
            },
        ),
        migrations.RemoveField(
            model_name='vinile',
            name='formato',
        ),
        migrations.AddField(
            model_name='vinile',
            name='dimensione',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vinile',
            name='formati',
            field=models.ManyToManyField(to='vinili.formato'),
        ),
    ]
