# Generated by Django 6.0.1 on 2026-04-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinili', '0005_formato_remove_vinile_formato_vinile_dimensione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinile',
            name='is_selection',
            field=models.BooleanField(default=False, verbose_name='Nostra Selezione'),
        ),
        migrations.AddField(
            model_name='vinile',
            name='is_trending',
            field=models.BooleanField(default=False, verbose_name='In Tendenza'),
        ),
    ]
