# Generated by Django 6.0.1 on 2026-05-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinili', '0006_vinile_is_selection_vinile_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinile',
            name='descrizione',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione'),
        ),
    ]
