# Generated by Django 6.0.1 on 2026-05-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinili', '0007_vinile_descrizione'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desideratoin',
            options={'verbose_name_plural': 'DesideratiIn'},
        ),
        migrations.AlterModelOptions(
            name='possiede',
            options={'verbose_name_plural': 'Possiedi'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'Wishlist'},
        ),
    ]
