# Generated by Django 6.0.1 on 2026-05-06 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinili', '0008_alter_desideratoin_options_alter_possiede_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('durata', models.CharField(blank=True, help_text='Formato MM:SS', max_length=10, null=True)),
                ('posizione', models.CharField(help_text='Esempio: A1, A2, B1...', max_length=5)),
                ('vinile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brani', to='vinili.vinile')),
            ],
            options={
                'verbose_name_plural': 'Brani',
            },
        ),
    ]
