# Generated by Django 6.0.1 on 2026-05-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinili', '0009_brano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brano',
            options={'ordering': ['posizione'], 'verbose_name_plural': 'Brani'},
        ),
    ]
